#!/bin/sh

# Swap left super/alt
xmodmap -e 'remove mod1 = Alt_L'
xmodmap -e 'remove mod4 = Super_L'
xmodmap -e 'add mod1 = Super_L'
xmodmap -e 'add mod4 = Alt_L'

# input method
if which uim >/dev/null; then
	export XMODIFIERS="@im=uim"
	export XIM_PROGRAM=`which uim-xim`
	export GTK_IM_MODULE="uim"
	export QT_IM_MODULE="uim"
	uim-xim &
fi

# composite manager
if which xcompmgr; then
	xcompmgr &
fi >/dev/null

