#!/bin/sh

# keyboard
setxkbmap kr kr104

# UIM toolbar
if [ -e `which uim-xim` ]; then
	uim-toolbar-gtk &
fi

# composite manager
if which compton; then
	compton &
fi >/dev/null

# GTK config file location, for QT
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

